# Generated by Django 5.1.2 on 2024-10-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('buff', 'buff'), ('chicken', 'chicken'), ('veg', 'veg')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='iamges')),
            ],
        ),
    ]
