# Generated by Django 5.1.2 on 2024-10-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
